import AppKit
import Observation

/// Explicitly enabled text history. Screenshots continue to live in the existing library.
@MainActor @Observable
final class NotchShelfStore {
    static let shared = NotchShelfStore()
    static let colorsKey = "bs_notchClipboardColors"
    static var keepsColors: Bool { UserDefaults.standard.object(forKey: colorsKey) as? Bool ?? true }
    static let enabledKey = "bs_notchClipboardHistory"
    struct Entry: Codable, Identifiable, Equatable {
        var id = UUID()
        var text: String
        var imageURL: URL?
        var date = Date()
        var isColor: Bool? = nil
    }
    private(set) var entries: [Entry] = []
    var error: String?
    @ObservationIgnored private var timer: Timer?
    @ObservationIgnored private var changeCount = -1
    private let fileURL: URL

    init(directory: URL? = nil) {
        let root = directory ?? (ProcessInfo.processInfo.environment["BETTERSHOT_TESTING"] == "1"
            ? FileManager.default.temporaryDirectory.appendingPathComponent("YayaShotShelfTests-\(UUID())")
            : FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0].appendingPathComponent("YayaShot/Shelf"))
        fileURL = root.appendingPathComponent("text.json")
        if let data = try? Data(contentsOf: fileURL), let saved = try? JSONDecoder().decode([Entry].self, from: data) {
            entries = Array(saved.prefix(50))
        }
    }

    func refreshMonitoring() {
        timer?.invalidate()
        timer = nil
        // Enabling history starts with the *next* copy, not previously copied private content.
        changeCount = NSPasteboard.general.changeCount
        guard AppPreferences.presentationMode == .notch, (UserDefaults.standard.bool(forKey: Self.enabledKey) || Self.keepsColors),
              ProcessInfo.processInfo.environment["BETTERSHOT_TESTING"] != "1" else { return }
        timer = Timer.scheduledTimer(withTimeInterval: 0.75, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.readClipboard(includeText: UserDefaults.standard.bool(forKey: Self.enabledKey), includeColors: Self.keepsColors) }
        }
        timer?.tolerance = 0.25
    }

    func readClipboard(_ pasteboard: NSPasteboard = .general, includeText: Bool = true, includeColors: Bool = true) {
        guard AppPreferences.presentationMode == .notch, changeCount != pasteboard.changeCount else { return }
        changeCount = pasteboard.changeCount
        let excluded = ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType",
                        "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword",
                        "com.yahyaelghobashy.yayashot.voice-capture"]
        guard !excluded.contains(where: { pasteboard.types?.contains(.init($0)) == true }),
              let text = pasteboard.string(forType: .string) else { return }
        // Captured OCR/colors have already been retained with their type.
        guard entries.first?.text != text else { return }
        let isColor = Self.isHexColor(text)
        guard isColor ? includeColors : includeText else { return }
        add(text: text, isColor: isColor)
    }

    /// A standalone CSS hex literal is a color; prose and bare numbers stay text.
    static func isHexColor(_ text: String) -> Bool {
        let value = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard value.first == "#", [4, 7].contains(value.count) else { return false }
        return value.dropFirst().utf8.allSatisfy { (48...57).contains($0) || (65...70).contains($0) || (97...102).contains($0) }
    }

    func add(text: String, imageURL: URL? = nil, isColor: Bool = false) {
        guard AppPreferences.presentationMode == .notch, !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty,
              text.utf8.count <= 100_000 else { return }
        entries.removeAll { $0.text == text && $0.imageURL == imageURL && ($0.isColor ?? false) == isColor }
        entries.insert(Entry(text: text, imageURL: imageURL, isColor: isColor), at: 0)
        entries = Array(entries.prefix(50))
        persist()
    }

    func remove(_ id: UUID) {
        if let entry = entries.first(where: { $0.id == id }) {
            if NotchPresenter.shared.ocrText == entry.text { NotchPresenter.shared.ocrText = nil }
            if NotchPresenter.shared.colorHex == entry.text { NotchPresenter.shared.colorHex = nil }
        }
        entries.removeAll { $0.id == id }
        persist()
    }
    func clear() {
        entries.removeAll()
        NotchPresenter.shared.ocrText = nil
        NotchPresenter.shared.colorHex = nil
        persist()
    }

    private func persist() {
        do {
            try FileManager.default.createDirectory(at: fileURL.deletingLastPathComponent(), withIntermediateDirectories: true,
                                                    attributes: [.posixPermissions: 0o700])
            try JSONEncoder().encode(entries).write(to: fileURL, options: .atomic)
            try FileManager.default.setAttributes([.posixPermissions: 0o600], ofItemAtPath: fileURL.path)
            error = nil
        } catch { self.error = "Couldn’t save shelf history. Check available disk space and try again." }
    }

    @discardableResult
    static func copy(_ entry: Entry, to pasteboard: NSPasteboard = .general) throws -> Bool {
        if let url = entry.imageURL {
            try ScreenshotFileActions.copyPNGToClipboard(from: url, text: entry.text, to: pasteboard)
            return pasteboard.string(forType: .string) == entry.text && pasteboard.data(forType: .png) != nil
        }
        return CaptureOrchestrator.copyText(entry.text, to: pasteboard)
    }
}
